version: '3'
services:
  recipes:
    image: 'recipes:1.0.6'
    env_file:
      - ./.env.docker
    networks:
      - lan
    ports:
      - '3000:3000'

  db:
    image: 'mysql:5.7'
    volumes:
      - /opt/docker-volumes/recipes:/var/lib/mysql
    env_file:
      - ./.env.docker
    networks:
      - lan
    ports:
      - '3306:3306'

  nginx:
    image: 'nginx:1.0.0'
    networks:
      - lan
    ports:
      - '8080:8080'

networks:
  lan:
